// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using TraderAi.Data;

#nullable disable

namespace TraderAi.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260712193724_AddLuldPriceBands")]
    partial class AddLuldPriceBands
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.9");

            modelBuilder.Entity("TraderAi.Models.Auditor", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Auditors");
                });

            modelBuilder.Entity("TraderAi.Models.Bank", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("Balance")
                        .HasPrecision(18, 2)
                        .HasColumnType("TEXT");

                    b.Property<decimal>("InterestRatePerCycle")
                        .HasPrecision(18, 6)
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Banks");
                });

            modelBuilder.Entity("TraderAi.Models.Bankruptcy", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("CashLost")
                        .HasPrecision(18, 2)
                        .HasColumnType("TEXT");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("ParticipantId")
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("ShareWorth")
                        .HasPrecision(18, 2)
                        .HasColumnType("TEXT");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("TriggeredAt")
                        .HasColumnType("TEXT");

                    b.Property<int>("TriggeredInCycleId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("Bankruptcies");
                });

            modelBuilder.Entity("TraderAi.Models.CollectiveFund", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("ClosedAt")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<int>("CreatedInCycleId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("FoundedByParticipantId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("IdleCycles")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsPlayerManaged")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("LastAdvertisedInCycleNumber")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("LastGrowthNewsInCycleNumber")
                        .HasColumnType("INTEGER");

                    b.Property<int>("ParticipantId")
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("PeakNetWorth")
                        .HasPrecision(18, 2)
                        .HasColumnType("TEXT");

                    b.Property<int>("PopularityIndex")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("CollectiveFunds");
                });

            modelBuilder.Entity("TraderAi.Models.CollectiveFundMembershipEvent", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("Amount")
                        .HasPrecision(18, 2)
                        .HasColumnType("TEXT");

                    b.Property<int>("CollectiveFundId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<int>("CreatedInCycleId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("FundParticipantId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("ParticipantId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("FundParticipantId", "Id");

                    b.HasIndex("ParticipantId", "Id");

                    b.ToTable("CollectiveFundMembershipEvents");
                });

            modelBuilder.Entity("TraderAi.Models.CollectiveFundParticipant", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("CollectiveFundId")
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("DepositAmount")
                        .HasPrecision(18, 2)
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsLeaving")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("JoinedAt")
                        .HasColumnType("TEXT");

                    b.Property<int>("JoinedInCycleId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("LeaveRampCycles")
                        .HasColumnType("INTEGER");

                    b.Property<int>("ParticipantId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("TenureCycles")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("CollectiveFundId");

                    b.ToTable("CollectiveFundParticipants");
                });

            modelBuilder.Entity("TraderAi.Models.Company", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("CashBalance")
                        .HasPrecision(18, 2)
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("ClosedAt")
                        .HasColumnType("TEXT");

                    b.Property<int?>("ClosedInCycleId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<int?>("CreatedInCycleId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("IndustryId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("IssuedSharesCount")
                        .HasColumnType("INTEGER");

                    b.Property<decimal?>("LastDividendCapitalization")
                        .HasPrecision(18, 2)
                        .HasColumnType("TEXT");

                    b.Property<int?>("LastMergedInCycleId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Companies");
                });

            modelBuilder.Entity("TraderAi.Models.CompanyRating", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("AuditorId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("CompanyId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<int>("CreatedInCycleId")
                        .HasColumnType("INTEGER");

                    b.Property<decimal?>("ImpactPercent")
                        .HasPrecision(18, 2)
                        .HasColumnType("TEXT");

                    b.Property<string>("Rating")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("CompanyId", "CreatedInCycleId");

                    b.ToTable("CompanyRatings");
                });

            modelBuilder.Entity("TraderAi.Models.CorporateCashTransaction", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("Amount")
                        .HasPrecision(18, 2)
                        .HasColumnType("TEXT");

                    b.Property<int>("CompanyId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<int>("CreatedInCycleId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("CompanyId", "Id");

                    b.ToTable("CorporateCashTransactions");
                });

            modelBuilder.Entity("TraderAi.Models.Crisis", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("DurationCycles")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Scope")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("TriggeredAt")
                        .HasColumnType("TEXT");

                    b.Property<int>("TriggeredInCycleId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("TriggeredInCycleNumber")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("Crises");
                });

            modelBuilder.Entity("TraderAi.Models.CrisisEvent", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int?>("CompanyId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<int>("CreatedInCycleId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("CreatedInCycleNumber")
                        .HasColumnType("INTEGER");

                    b.Property<int>("CrisisId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<decimal?>("ImpactPercent")
                        .HasPrecision(18, 2)
                        .HasColumnType("TEXT");

                    b.Property<int?>("IndustryId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("CrisisId");

                    b.ToTable("CrisisEvents");
                });

            modelBuilder.Entity("TraderAi.Models.CrisisIndustry", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("CrisisId")
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("ImpactPercent")
                        .HasPrecision(18, 2)
                        .HasColumnType("TEXT");

                    b.Property<int>("IndustryId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("CrisisId");

                    b.ToTable("CrisisIndustries");
                });

            modelBuilder.Entity("TraderAi.Models.DividendPayout", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("Amount")
                        .HasPrecision(18, 2)
                        .HasColumnType("TEXT");

                    b.Property<int>("CompanyId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<int>("CreatedInCycleId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("MoneyTransactionId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("CreatedInCycleId");

                    b.HasIndex("MoneyTransactionId");

                    b.ToTable("DividendPayouts");
                });

            modelBuilder.Entity("TraderAi.Models.Holding", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("AverageCost")
                        .HasPrecision(18, 2)
                        .HasColumnType("TEXT");

                    b.Property<int>("CompanyId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("ParticipantId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Quantity")
                        .HasColumnType("INTEGER");

                    b.Property<int>("SettledQuantity")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("CompanyId");

                    b.HasIndex("ParticipantId", "CompanyId")
                        .IsUnique();

                    b.ToTable("Holdings");
                });

            modelBuilder.Entity("TraderAi.Models.Industry", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<decimal>("SectorBeta")
                        .ValueGeneratedOnAdd()
                        .HasPrecision(18, 2)
                        .HasColumnType("TEXT")
                        .HasDefaultValue(1m);

                    b.Property<int>("SentimentValue")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValue(0);

                    b.Property<decimal>("SentimentVolatility")
                        .ValueGeneratedOnAdd()
                        .HasPrecision(18, 2)
                        .HasColumnType("TEXT")
                        .HasDefaultValue(0m);

                    b.HasKey("Id");

                    b.ToTable("Industries");
                });

            modelBuilder.Entity("TraderAi.Models.Loan", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("AccruedFees")
                        .HasPrecision(18, 2)
                        .HasColumnType("TEXT");

                    b.Property<int>("BankId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("CloseReason")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("ClosedAt")
                        .HasColumnType("TEXT");

                    b.Property<int?>("ClosedInCycleId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<int>("DistressDiscountStep")
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("InterestRatePerCycle")
                        .HasPrecision(18, 6)
                        .HasColumnType("TEXT");

                    b.Property<int>("OpenedInCycleId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("ParticipantId")
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("PastDueInterest")
                        .HasPrecision(18, 2)
                        .HasColumnType("TEXT");

                    b.Property<decimal>("PastDuePrincipal")
                        .HasPrecision(18, 2)
                        .HasColumnType("TEXT");

                    b.Property<decimal>("Principal")
                        .HasPrecision(18, 2)
                        .HasColumnType("TEXT");

                    b.Property<decimal>("RemainingPrincipal")
                        .HasPrecision(18, 2)
                        .HasColumnType("TEXT");

                    b.Property<decimal>("ScheduledInstallment")
                        .HasPrecision(18, 2)
                        .HasColumnType("TEXT");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("TermCycles")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("BankId", "Status");

                    b.HasIndex("ParticipantId", "Status");

                    b.ToTable("Loans");
                });

            modelBuilder.Entity("TraderAi.Models.MarginAccount", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("AccruedInterest")
                        .HasPrecision(18, 2)
                        .HasColumnType("TEXT");

                    b.Property<decimal>("DebitBalance")
                        .HasPrecision(18, 2)
                        .HasColumnType("TEXT");

                    b.Property<decimal>("InitialMarginRate")
                        .HasPrecision(18, 2)
                        .HasColumnType("TEXT");

                    b.Property<int?>("LastInterestAccruedTradingDayId")
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("MaintenanceMarginRate")
                        .HasPrecision(18, 2)
                        .HasColumnType("TEXT");

                    b.Property<int>("ParticipantId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("ParticipantId")
                        .IsUnique();

                    b.ToTable("MarginAccounts");
                });

            modelBuilder.Entity("TraderAi.Models.MarginCall", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("AccountEquity")
                        .HasPrecision(18, 2)
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("ClosedAt")
                        .HasColumnType("TEXT");

                    b.Property<int?>("ClosedInTradingDayId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("Deficiency")
                        .HasPrecision(18, 2)
                        .HasColumnType("TEXT");

                    b.Property<decimal>("MaintenanceRequirement")
                        .HasPrecision(18, 2)
                        .HasColumnType("TEXT");

                    b.Property<int>("MarginAccountId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("OpenedInCycleId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("OpenedInTradingDayId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("MarginAccountId", "Status");

                    b.ToTable("MarginCalls");
                });

            modelBuilder.Entity("TraderAi.Models.Market", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("CompanyClosuresSinceLastAppearance")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<int?>("CurrentCycleId")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("CurrentTradingDayId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("LastCompanyAppearanceCycleNumber")
                        .HasColumnType("INTEGER");

                    b.Property<int>("LastGlobalCrisisCycleNumber")
                        .HasColumnType("INTEGER");

                    b.Property<int>("LastLocalCrisisCycleNumber")
                        .HasColumnType("INTEGER");

                    b.Property<int>("LastScienceInvestigationCycleNumber")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("NextDividendCycleNumber")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Markets");
                });

            modelBuilder.Entity("TraderAi.Models.MarketCycle", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("CompletedAt")
                        .HasColumnType("TEXT");

                    b.Property<int>("CycleNumber")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("StartedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("TradingCycleNumber")
                        .HasColumnType("INTEGER");

                    b.Property<int>("TradingDayId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("CycleNumber")
                        .IsUnique();

                    b.HasIndex("TradingDayId", "TradingCycleNumber")
                        .IsUnique()
                        .HasFilter("TradingDayId > 0");

                    b.ToTable("MarketCycles");
                });

            modelBuilder.Entity("TraderAi.Models.MarketExit", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("InitialBalance")
                        .HasPrecision(18, 2)
                        .HasColumnType("TEXT");

                    b.Property<int>("JoinedInCycleId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("LeftAt")
                        .HasColumnType("TEXT");

                    b.Property<int>("LeftInCycleId")
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("MaxTotalWorth")
                        .HasPrecision(18, 2)
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("OrdersPlaced")
                        .HasColumnType("INTEGER");

                    b.Property<int>("ParticipantId")
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("QuitBalance")
                        .HasPrecision(18, 2)
                        .HasColumnType("TEXT");

                    b.Property<string>("Reason")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("MarketExits");
                });

            modelBuilder.Entity("TraderAi.Models.MoneyTransaction", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("Amount")
                        .HasPrecision(18, 2)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<int>("CreatedInCycleId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("ParticipantId")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("RelatedLoanId")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("RelatedOrderId")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("RelatedShareTransactionId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("CreatedInCycleId");

                    b.HasIndex("RelatedLoanId");

                    b.HasIndex("RelatedOrderId");

                    b.HasIndex("RelatedShareTransactionId");

                    b.ToTable("MoneyTransactions");
                });

            modelBuilder.Entity("TraderAi.Models.MoneyTransactionArchive", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("Amount")
                        .HasPrecision(18, 2)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<int>("CreatedInCycleId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("ParticipantId")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("RelatedLoanId")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("RelatedOrderId")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("RelatedShareTransactionId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("MoneyTransactionArchives");
                });

            modelBuilder.Entity("TraderAi.Models.NewsPost", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Direction")
                        .HasColumnType("TEXT");

                    b.Property<int?>("ImpactAppliedInCycleId")
                        .HasColumnType("INTEGER");

                    b.Property<decimal?>("ImpactPercent")
                        .HasPrecision(18, 2)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("PublishedAt")
                        .HasColumnType("TEXT");

                    b.Property<int>("PublishedInCycleId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Scope")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int?>("TargetCompanyId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("NewsPosts");
                });

            modelBuilder.Entity("TraderAi.Models.NewsPostIndustry", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("IndustryId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("NewsPostId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("NewsPostId");

                    b.ToTable("NewsPostIndustries");
                });

            modelBuilder.Entity("TraderAi.Models.Order", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("CompanyId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<int>("CreatedInCycleId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("FilledQuantity")
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("LimitPrice")
                        .HasPrecision(18, 2)
                        .HasColumnType("TEXT");

                    b.Property<int?>("ParticipantId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Quantity")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("RelatedLoanId")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("RelatedMarginCallId")
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("ReservedCashAmount")
                        .HasPrecision(18, 2)
                        .HasColumnType("TEXT");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Status");

                    b.HasIndex("RelatedLoanId", "Status");

                    b.HasIndex("RelatedMarginCallId", "Status");

                    b.HasIndex("ParticipantId", "CompanyId", "Type", "Status");

                    b.ToTable("Orders");
                });

            modelBuilder.Entity("TraderAi.Models.OrderFill", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("BuyOrderId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<int>("CreatedInCycleId")
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("ExecutionPrice")
                        .HasPrecision(18, 2)
                        .HasColumnType("TEXT");

                    b.Property<int>("Quantity")
                        .HasColumnType("INTEGER");

                    b.Property<int>("SellOrderId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("ShareTransactionId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("ShareTransactionId");

                    b.ToTable("OrderFills");
                });

            modelBuilder.Entity("TraderAi.Models.Participant", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("BankruptcyDiscountStep")
                        .HasColumnType("INTEGER");

                    b.Property<int>("BankruptcyOwnedAtStart")
                        .HasColumnType("INTEGER");

                    b.Property<int>("CannotBuyCycles")
                        .HasColumnType("INTEGER");

                    b.Property<int>("CashStarvedCycles")
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("CurrentBalance")
                        .HasPrecision(18, 2)
                        .HasColumnType("TEXT");

                    b.Property<decimal>("InitialBalance")
                        .HasPrecision(18, 2)
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsActive")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsBankrupt")
                        .HasColumnType("INTEGER");

                    b.Property<int>("JoinedInCycleId")
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("MaxTotalWorth")
                        .HasPrecision(18, 2)
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool>("PendingFundLossExitRoll")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("PendingFundSwitch")
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("ReservedBalance")
                        .HasPrecision(18, 2)
                        .HasColumnType("TEXT");

                    b.Property<string>("RiskProfile")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<decimal>("RiskProfileIndex")
                        .HasPrecision(18, 6)
                        .HasColumnType("TEXT");

                    b.Property<decimal>("SettledCashBalance")
                        .HasPrecision(18, 2)
                        .HasColumnType("TEXT");

                    b.Property<string>("Temperament")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<decimal>("TemperamentIndex")
                        .HasPrecision(18, 6)
                        .HasColumnType("TEXT");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("WealthyCycles")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("Participants");
                });

            modelBuilder.Entity("TraderAi.Models.ParticipantWorthSnapshot", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("Balance")
                        .HasPrecision(18, 2)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<int>("CreatedInCycleId")
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("HoldingsValue")
                        .HasPrecision(18, 2)
                        .HasColumnType("TEXT");

                    b.Property<decimal>("LoanLiability")
                        .HasPrecision(18, 2)
                        .HasColumnType("TEXT");

                    b.Property<decimal>("MarginLiability")
                        .HasPrecision(18, 2)
                        .HasColumnType("TEXT");

                    b.Property<int>("ParticipantId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("CreatedInCycleId");

                    b.HasIndex("ParticipantId", "CreatedInCycleId");

                    b.ToTable("ParticipantWorthSnapshots");
                });

            modelBuilder.Entity("TraderAi.Models.ParticipantWorthSnapshotArchive", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("Balance")
                        .HasPrecision(18, 2)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<int>("CreatedInCycleId")
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("HoldingsValue")
                        .HasPrecision(18, 2)
                        .HasColumnType("TEXT");

                    b.Property<decimal>("LoanLiability")
                        .HasPrecision(18, 2)
                        .HasColumnType("TEXT");

                    b.Property<decimal>("MarginLiability")
                        .HasPrecision(18, 2)
                        .HasColumnType("TEXT");

                    b.Property<int>("ParticipantId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("ParticipantWorthSnapshotArchives");
                });

            modelBuilder.Entity("TraderAi.Models.PriceBandState", b =>
                {
                    b.Property<int>("CompanyId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("LimitDirection")
                        .HasColumnType("TEXT");

                    b.Property<int?>("LimitStateStartedCycleNumber")
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("LowerBandPrice")
                        .HasPrecision(18, 2)
                        .HasColumnType("TEXT");

                    b.Property<int?>("PauseUntilCycleNumber")
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("ReferencePrice")
                        .HasPrecision(18, 2)
                        .HasColumnType("TEXT");

                    b.Property<string>("State")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("UpdatedInCycleId")
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("UpperBandPrice")
                        .HasPrecision(18, 2)
                        .HasColumnType("TEXT");

                    b.HasKey("CompanyId");

                    b.ToTable("PriceBandStates");
                });

            modelBuilder.Entity("TraderAi.Models.PriceSnapshot", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<decimal?>("Capitalization")
                        .HasPrecision(18, 2)
                        .HasColumnType("TEXT");

                    b.Property<int>("CompanyId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<int>("CreatedInCycleId")
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("Price")
                        .HasPrecision(18, 2)
                        .HasColumnType("TEXT");

                    b.Property<int?>("SourceShareTransactionId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("CreatedInCycleId");

                    b.HasIndex("SourceShareTransactionId");

                    b.HasIndex("CompanyId", "Id");

                    b.ToTable("PriceSnapshots");
                });

            modelBuilder.Entity("TraderAi.Models.PriceSnapshotArchive", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<decimal?>("Capitalization")
                        .HasPrecision(18, 2)
                        .HasColumnType("TEXT");

                    b.Property<int>("CompanyId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<int>("CreatedInCycleId")
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("Price")
                        .HasPrecision(18, 2)
                        .HasColumnType("TEXT");

                    b.Property<int?>("SourceShareTransactionId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("PriceSnapshotArchives");
                });

            modelBuilder.Entity("TraderAi.Models.ScienceInvestigation", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("TriggeredAt")
                        .HasColumnType("TEXT");

                    b.Property<int>("TriggeredInCycleId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("ScienceInvestigations");
                });

            modelBuilder.Entity("TraderAi.Models.ScienceInvestigationIndustry", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("ImpactPercent")
                        .HasPrecision(18, 2)
                        .HasColumnType("TEXT");

                    b.Property<int>("IndustryId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("ScienceInvestigationId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("ScienceInvestigationId");

                    b.ToTable("ScienceInvestigationIndustries");
                });

            modelBuilder.Entity("TraderAi.Models.SectorSentimentSnapshot", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<int>("CreatedInCycleId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("IndustryId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("SentimentValue")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("CreatedInCycleId");

                    b.HasIndex("IndustryId");

                    b.ToTable("SectorSentimentSnapshots");
                });

            modelBuilder.Entity("TraderAi.Models.SectorSentimentSnapshotArchive", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<int>("CreatedInCycleId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("IndustryId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("SentimentValue")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("CreatedInCycleId");

                    b.ToTable("SectorSentimentSnapshotArchives");
                });

            modelBuilder.Entity("TraderAi.Models.SettlementInstruction", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("BuyerId")
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("BuyerMarginAdvance")
                        .HasPrecision(18, 2)
                        .HasColumnType("TEXT");

                    b.Property<decimal>("CashAmount")
                        .HasPrecision(18, 2)
                        .HasColumnType("TEXT");

                    b.Property<int>("CompanyId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<int>("CreatedInCycleId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("DueDayNumber")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Quantity")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("SellerId")
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("SellerMarginDebitRepayment")
                        .HasPrecision(18, 2)
                        .HasColumnType("TEXT");

                    b.Property<decimal>("SellerMarginInterestPayment")
                        .HasPrecision(18, 2)
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("SettledAt")
                        .HasColumnType("TEXT");

                    b.Property<int?>("SettledInCycleId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("ShareTransactionId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("TradeDayNumber")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("ShareTransactionId")
                        .IsUnique();

                    b.HasIndex("Status", "DueDayNumber");

                    b.HasIndex("BuyerId", "Status", "DueDayNumber");

                    b.HasIndex("SellerId", "Status", "DueDayNumber");

                    b.ToTable("SettlementInstructions");
                });

            modelBuilder.Entity("TraderAi.Models.ShareEmission", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("CompanyId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<int>("CreatedInCycleId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("RecipientCount")
                        .HasColumnType("INTEGER");

                    b.Property<int>("SharesEmitted")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("ShareEmissions");
                });

            modelBuilder.Entity("TraderAi.Models.ShareTransaction", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("BuyerId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("CompanyId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<int>("CreatedInCycleId")
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("Price")
                        .HasPrecision(18, 2)
                        .HasColumnType("TEXT");

                    b.Property<int>("Quantity")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("SellerId")
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("TotalCost")
                        .HasPrecision(18, 2)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("ShareTransactions");
                });

            modelBuilder.Entity("TraderAi.Models.TradingBreakCycle", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("DurationSeconds")
                        .HasColumnType("INTEGER");

                    b.Property<int>("ElapsedSeconds")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsActive")
                        .HasColumnType("INTEGER");

                    b.Property<int>("StartedAfterCycleId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("TradingDayId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("TradingDayId", "IsActive");

                    b.ToTable("TradingBreakCycles");
                });

            modelBuilder.Entity("TraderAi.Models.TradingDay", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int?>("ClosedInCycleId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("DayNumber")
                        .HasColumnType("INTEGER");

                    b.Property<int>("OpenedInCycleId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("State")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("DayNumber")
                        .IsUnique();

                    b.ToTable("TradingDays");
                });

            modelBuilder.Entity("TraderAi.Models.CollectiveFundParticipant", b =>
                {
                    b.HasOne("TraderAi.Models.CollectiveFund", null)
                        .WithMany("Members")
                        .HasForeignKey("CollectiveFundId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("TraderAi.Models.CorporateCashTransaction", b =>
                {
                    b.HasOne("TraderAi.Models.Company", null)
                        .WithMany()
                        .HasForeignKey("CompanyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("TraderAi.Models.CrisisEvent", b =>
                {
                    b.HasOne("TraderAi.Models.Crisis", null)
                        .WithMany("Events")
                        .HasForeignKey("CrisisId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("TraderAi.Models.CrisisIndustry", b =>
                {
                    b.HasOne("TraderAi.Models.Crisis", null)
                        .WithMany("Industries")
                        .HasForeignKey("CrisisId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("TraderAi.Models.DividendPayout", b =>
                {
                    b.HasOne("TraderAi.Models.MoneyTransaction", "MoneyTransaction")
                        .WithMany()
                        .HasForeignKey("MoneyTransactionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("MoneyTransaction");
                });

            modelBuilder.Entity("TraderAi.Models.Loan", b =>
                {
                    b.HasOne("TraderAi.Models.Bank", "Bank")
                        .WithMany()
                        .HasForeignKey("BankId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Bank");
                });

            modelBuilder.Entity("TraderAi.Models.MoneyTransaction", b =>
                {
                    b.HasOne("TraderAi.Models.Order", "RelatedOrder")
                        .WithMany()
                        .HasForeignKey("RelatedOrderId");

                    b.HasOne("TraderAi.Models.ShareTransaction", "RelatedShareTransaction")
                        .WithMany()
                        .HasForeignKey("RelatedShareTransactionId");

                    b.Navigation("RelatedOrder");

                    b.Navigation("RelatedShareTransaction");
                });

            modelBuilder.Entity("TraderAi.Models.NewsPostIndustry", b =>
                {
                    b.HasOne("TraderAi.Models.NewsPost", null)
                        .WithMany("Industries")
                        .HasForeignKey("NewsPostId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("TraderAi.Models.OrderFill", b =>
                {
                    b.HasOne("TraderAi.Models.ShareTransaction", "ShareTransaction")
                        .WithMany()
                        .HasForeignKey("ShareTransactionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ShareTransaction");
                });

            modelBuilder.Entity("TraderAi.Models.PriceBandState", b =>
                {
                    b.HasOne("TraderAi.Models.Company", "Company")
                        .WithOne("PriceBandState")
                        .HasForeignKey("TraderAi.Models.PriceBandState", "CompanyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Company");
                });

            modelBuilder.Entity("TraderAi.Models.PriceSnapshot", b =>
                {
                    b.HasOne("TraderAi.Models.ShareTransaction", "SourceShareTransaction")
                        .WithMany()
                        .HasForeignKey("SourceShareTransactionId");

                    b.Navigation("SourceShareTransaction");
                });

            modelBuilder.Entity("TraderAi.Models.ScienceInvestigationIndustry", b =>
                {
                    b.HasOne("TraderAi.Models.ScienceInvestigation", null)
                        .WithMany("Industries")
                        .HasForeignKey("ScienceInvestigationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("TraderAi.Models.SectorSentimentSnapshot", b =>
                {
                    b.HasOne("TraderAi.Models.MarketCycle", null)
                        .WithMany()
                        .HasForeignKey("CreatedInCycleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("TraderAi.Models.Industry", null)
                        .WithMany()
                        .HasForeignKey("IndustryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("TraderAi.Models.SettlementInstruction", b =>
                {
                    b.HasOne("TraderAi.Models.ShareTransaction", "ShareTransaction")
                        .WithOne("SettlementInstruction")
                        .HasForeignKey("TraderAi.Models.SettlementInstruction", "ShareTransactionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ShareTransaction");
                });

            modelBuilder.Entity("TraderAi.Models.CollectiveFund", b =>
                {
                    b.Navigation("Members");
                });

            modelBuilder.Entity("TraderAi.Models.Company", b =>
                {
                    b.Navigation("PriceBandState");
                });

            modelBuilder.Entity("TraderAi.Models.Crisis", b =>
                {
                    b.Navigation("Events");

                    b.Navigation("Industries");
                });

            modelBuilder.Entity("TraderAi.Models.NewsPost", b =>
                {
                    b.Navigation("Industries");
                });

            modelBuilder.Entity("TraderAi.Models.ScienceInvestigation", b =>
                {
                    b.Navigation("Industries");
                });

            modelBuilder.Entity("TraderAi.Models.ShareTransaction", b =>
                {
                    b.Navigation("SettlementInstruction");
                });
#pragma warning restore 612, 618
        }
    }
}
